#**MM/GBSA Energy Components - 5FWJ metal-retained**

In [1]:
from pathlib import Path

print("Current folder:")
print(Path.cwd())

print("\nFiles here:")
for f in Path.cwd().iterdir():
    print(f.name)

Current folder:
/content

Files here:
.config
FINAL_RESULTS_MMGBSA_holo_rep1.dat
FINAL_RESULTS_PER_FRAME_apo_rep2.dat
FINAL_RESULTS_MMGBSA_PAF_rep2.dat
FINAL_RESULTS_MMGBSA_CAF_rep1.dat
FINAL_RESULTS_MMGBSA_holo_rep3.dat
FINAL_RESULTS_PER_FRAME_holo_rep2.dat
FINAL_RESULTS_PER_FRAME_PAF_rep_3.dat
FINAL_RESULTS_MMGBSA_CAF_rep3.dat
FINAL_RESULTS_MMGBSA_CAF_rep2.dat
FINAL_RESULTS_MMGBSA_PAF_rep3.dat
FINAL_RESULTS_PER_FRAME_holo_rep_1.dat
FINAL_RESULTS_PER_FRAME_PAF_rep1.dat
FINAL_RESULTS_PER_FRAME_holo_rep_3.dat
FINAL_RESULTS_MMGBSA_apo_rep1.dat
FINAL_RESULTS_MMGBSA_holo_rep2.dat
FINAL_RESULTS_PER_FRAME_apo_rep3.dat
FINAL_RESULTS_PER_FRAME_CAF_rep_2.dat
FINAL_RESULTS_MMGBSA_apo_rep2.dat
FINAL_RESULTS_PER_FRAME_PAF_rep2.dat
FINAL_RESULTS_PER_FRAME_CAF_rep1.dat
FINAL_RESULTS_PER_FRAME_CAF_rep_3.dat
FINAL_RESULTS_MMGBSA_PAF_rep1.dat
FINAL_RESULTS_PER_FRAME_apo_rep1.dat
FINAL_RESULTS_MMGBSA_apo_rep3.dat
sample_data

In [3]:
import re
import numpy as np
import pandas as pd
from pathlib import Path

rep_files = {
    "Rep 1": "FINAL_RESULTS_MMGBSA_holo_rep1.dat",
    "Rep 2": "FINAL_RESULTS_MMGBSA_holo_rep2.dat",
    "Rep 3": "FINAL_RESULTS_MMGBSA_holo_rep3.dat",
}

# delta variants: Greek Δ (U+0394) and increment ∆ (U+2206)
DELTA = r"[Δ∆]?"

TERMS = ["VDWAALS", "EEL", "EGB", "ESURF", "GGAS", "GSOLV", "TOTAL"]

def extract_delta_section(lines):
    # Find the header line, then take a window after it
    start_idx = None
    for i, ln in enumerate(lines):
        if "Delta (Complex - Receptor - Ligand)" in ln:
            start_idx = i
            break
    if start_idx is None:
        raise ValueError("Cannot find 'Delta (Complex - Receptor - Ligand)' section.")
    return lines[start_idx : min(start_idx + 300, len(lines))]

def parse_term_from_section(section_lines, term):
    # Match lines like: ∆TOTAL   -7.20   1.87  1.70  0.08  0.07
    pat = re.compile(
        rf"^\s*{DELTA}{re.escape(term)}\s+"
        rf"([-+]?\d+(?:\.\d+)?)\s+"
        rf"([-+]?\d+(?:\.\d+)?)\s+"
        rf"([-+]?\d+(?:\.\d+)?)\s+"
        rf"([-+]?\d+(?:\.\d+)?)\s+"
        rf"([-+]?\d+(?:\.\d+)?)\s*$"
    )
    for ln in section_lines:
        m = pat.match(ln)
        if m:
            avg, sd_prop, sd, sem_prop, sem = map(float, m.groups())
            return {"avg": avg, "sd": sd, "sem": sem, "line": ln}
    return None

# Run
rep_rows = []
rep_vals = {t: [] for t in TERMS}

for rep, fn in rep_files.items():
    p = Path(fn)
    if not p.exists():
        raise FileNotFoundError(f"Missing file: {fn}")

    lines = p.read_text(encoding="utf-8", errors="ignore").splitlines()
    section = extract_delta_section(lines)

    row = {"Replica": rep, "file": fn}
    for term in TERMS:
        got = parse_term_from_section(section, term)
        if got is None:
            row[f"{term} (avg)"] = np.nan
            row[f"{term} (SD within)"] = np.nan
        else:
            row[f"{term} (avg)"] = got["avg"]
            row[f"{term} (SD within)"] = got["sd"]
            rep_vals[term].append(got["avg"])
            if term == "TOTAL":
                row["Matched TOTAL line"] = got["line"]
    rep_rows.append(row)

df_rep = pd.DataFrame(rep_rows)
display(df_rep)

# Save per-replica table
df_rep.to_csv("MMGBSA_per_replica_5FWJ metal-retained_summary.csv", index=False, encoding="utf-8-sig")

# Summary mean ± SD across replicas (kcal/mol)
sum_rows = []
for term in TERMS:
    vals = np.array(rep_vals[term], dtype=float)
    if len(vals) != 3:
        sum_rows.append({"Term": term, "Mean ± SD (kcal/mol)": "NA (missing)"})
    else:
        sum_rows.append({"Term": term, "Mean ± SD (kcal/mol)": f"{vals.mean():.2f} ± {vals.std(ddof=1):.2f}"})

df_summary = pd.DataFrame(sum_rows)
df_summary.loc[df_summary["Term"] == "TOTAL", "Term"] = "ΔGbind (ΔTOTAL)"
display(df_summary)

# Save across-replica summary table
df_summary.to_csv("MMGBSA_across_replicas_5FWJ metal-retained_summary.csv", index=False, encoding="utf-8-sig")

print("Saved:")
print("- MMGBSA_per_replica_5FWJ metal-retained_summary.csv")
print("- MMGBSA_across_replicas_5FWJ metal-retained_summary.csv")

,Replica,file,VDWAALS (avg),VDWAALS (SD within),EEL (avg),EEL (SD within),EGB (avg),EGB (SD within),ESURF (avg),ESURF (SD within),GGAS (avg),GGAS (SD within),GSOLV (avg),GSOLV (SD within),TOTAL (avg),TOTAL (SD within),Matched TOTAL line
0,Rep 1,FINAL_RESULTS_MMGBSA_holo_rep1.dat,-5.01,7.38,-1.64,3.82,5.21,7.53,-0.67,1.01,-6.66,10.23,4.54,6.64,-2.12,4.21,ΔTOTAL -2.12 1.70 ...
1,Rep 2,FINAL_RESULTS_MMGBSA_holo_rep2.dat,-21.93,2.39,-7.83,3.32,30.08,3.58,-2.85,0.32,-29.76,4.57,27.24,3.47,-2.53,3.74,ΔTOTAL -2.53 1.57 ...
2,Rep 3,FINAL_RESULTS_MMGBSA_holo_rep3.dat,-0.00,0.01,-0.14,1.40,0.31,1.60,-0.00,0.00,-0.14,1.41,0.31,1.60,0.16,0.50,ΔTOTAL 0.16 1.87 ...

              Term Mean ± SD (kcal/mol)
0          VDWAALS        -8.98 ± 11.49
1              EEL         -3.20 ± 4.08
2              EGB        11.87 ± 15.96
3            ESURF         -1.17 ± 1.49
4             GGAS       -12.19 ± 15.56
5            GSOLV        10.70 ± 14.48
6  ΔGbind (ΔTOTAL)         -1.50 ± 1.45

Saved:
- MMGBSA_per_replica_5FWJ metal-retained_summary.csv
- MMGBSA_across_replicas_5FWJ metal-retained_summary.csv

#**MM/GBSA Energy Components - 5FWJ metal-depleted**

In [4]:
import re
import numpy as np
import pandas as pd
from pathlib import Path

rep_files = {
    "Rep 1": "FINAL_RESULTS_MMGBSA_apo_rep1.dat",
    "Rep 2": "FINAL_RESULTS_MMGBSA_apo_rep2.dat",
    "Rep 3": "FINAL_RESULTS_MMGBSA_apo_rep3.dat",
}

# delta variants: Greek Δ (U+0394) and increment ∆ (U+2206)
DELTA = r"[Δ∆]?"

TERMS = ["VDWAALS", "EEL", "EGB", "ESURF", "GGAS", "GSOLV", "TOTAL"]

def extract_delta_section(lines):
    # Find the header line, then take a window after it
    start_idx = None
    for i, ln in enumerate(lines):
        if "Delta (Complex - Receptor - Ligand)" in ln:
            start_idx = i
            break
    if start_idx is None:
        raise ValueError("Cannot find 'Delta (Complex - Receptor - Ligand)' section.")
    return lines[start_idx : min(start_idx + 300, len(lines))]

def parse_term_from_section(section_lines, term):
    # Match lines like: ∆TOTAL   -7.20   1.87  1.70  0.08  0.07
    pat = re.compile(
        rf"^\s*{DELTA}{re.escape(term)}\s+"
        rf"([-+]?\d+(?:\.\d+)?)\s+"
        rf"([-+]?\d+(?:\.\d+)?)\s+"
        rf"([-+]?\d+(?:\.\d+)?)\s+"
        rf"([-+]?\d+(?:\.\d+)?)\s+"
        rf"([-+]?\d+(?:\.\d+)?)\s*$"
    )
    for ln in section_lines:
        m = pat.match(ln)
        if m:
            avg, sd_prop, sd, sem_prop, sem = map(float, m.groups())
            return {"avg": avg, "sd": sd, "sem": sem, "line": ln}
    return None

# Run
rep_rows = []
rep_vals = {t: [] for t in TERMS}

for rep, fn in rep_files.items():
    p = Path(fn)
    if not p.exists():
        raise FileNotFoundError(f"Missing file: {fn}")

    lines = p.read_text(encoding="utf-8", errors="ignore").splitlines()
    section = extract_delta_section(lines)

    row = {"Replica": rep, "file": fn}
    for term in TERMS:
        got = parse_term_from_section(section, term)
        if got is None:
            row[f"{term} (avg)"] = np.nan
            row[f"{term} (SD within)"] = np.nan
        else:
            row[f"{term} (avg)"] = got["avg"]
            row[f"{term} (SD within)"] = got["sd"]
            rep_vals[term].append(got["avg"])
            if term == "TOTAL":
                row["Matched TOTAL line"] = got["line"]
    rep_rows.append(row)

df_rep = pd.DataFrame(rep_rows)
display(df_rep)

# Save per-replica table
df_rep.to_csv("MMGBSA_per_replica_5FWJ metal-depleted_summary.csv", index=False, encoding="utf-8-sig")

# Summary mean ± SD across replicas (kcal/mol)
sum_rows = []
for term in TERMS:
    vals = np.array(rep_vals[term], dtype=float)
    if len(vals) != 3:
        sum_rows.append({"Term": term, "Mean ± SD (kcal/mol)": "NA (missing)"})
    else:
        sum_rows.append({"Term": term, "Mean ± SD (kcal/mol)": f"{vals.mean():.2f} ± {vals.std(ddof=1):.2f}"})

df_summary = pd.DataFrame(sum_rows)
df_summary.loc[df_summary["Term"] == "TOTAL", "Term"] = "ΔGbind (ΔTOTAL)"
display(df_summary)

# Save across-replica summary table
df_summary.to_csv("MMGBSA_across_replicas_5FWJ metal-depleted_summary.csv", index=False, encoding="utf-8-sig")

print("Saved:")
print("- MMGBSA_per_replica_5FWJ metal-depleted_summary.csv")
print("- MMGBSA_across_replicas_5FWJ metal-depleted_summary.csv")

,Replica,file,VDWAALS (avg),VDWAALS (SD within),EEL (avg),EEL (SD within),EGB (avg),EGB (SD within),ESURF (avg),ESURF (SD within),GGAS (avg),GGAS (SD within),GSOLV (avg),GSOLV (SD within),TOTAL (avg),TOTAL (SD within),Matched TOTAL line
0,Rep 1,FINAL_RESULTS_MMGBSA_apo_rep1.dat,-0.00,0.00,0.00,0.11,-0.00,0.11,0.00,0.00,0.00,0.11,-0.00,0.11,-0.00,0.00,ΔTOTAL -0.00 2.00 ...
1,Rep 2,FINAL_RESULTS_MMGBSA_apo_rep2.dat,-9.55,8.16,-1.26,2.01,5.39,4.48,-1.17,0.97,-10.82,9.29,4.22,3.58,-6.60,6.00,ΔTOTAL -6.60 1.42 ...
2,Rep 3,FINAL_RESULTS_MMGBSA_apo_rep3.dat,-6.65,5.70,-0.70,1.60,4.42,3.55,-0.93,0.83,-7.36,6.54,3.49,2.83,-3.87,4.03,ΔTOTAL -3.87 1.51 ...

              Term Mean ± SD (kcal/mol)
0          VDWAALS         -5.40 ± 4.90
1              EEL         -0.65 ± 0.63
2              EGB          3.27 ± 2.87
3            ESURF         -0.70 ± 0.62
4             GGAS         -6.06 ± 5.53
5            GSOLV          2.57 ± 2.26
6  ΔGbind (ΔTOTAL)         -3.49 ± 3.32

Saved:
- MMGBSA_per_replica_5FWJ metal-depleted_summary.csv
- MMGBSA_across_replicas_5FWJ metal-depleted_summary.csv

#**MM/GBSA Energy Components - AlphaFold_PAF**

In [5]:
import re
import numpy as np
import pandas as pd
from pathlib import Path

rep_files = {
    "Rep 1": "FINAL_RESULTS_MMGBSA_PAF_rep1.dat",
    "Rep 2": "FINAL_RESULTS_MMGBSA_PAF_rep2.dat",
    "Rep 3": "FINAL_RESULTS_MMGBSA_PAF_rep3.dat",
}

# delta variants: Greek Δ (U+0394) and increment ∆ (U+2206)
DELTA = r"[Δ∆]?"

TERMS = ["VDWAALS", "EEL", "EGB", "ESURF", "GGAS", "GSOLV", "TOTAL"]

def extract_delta_section(lines):
    # Find the header line, then take a window after it
    start_idx = None
    for i, ln in enumerate(lines):
        if "Delta (Complex - Receptor - Ligand)" in ln:
            start_idx = i
            break
    if start_idx is None:
        raise ValueError("Cannot find 'Delta (Complex - Receptor - Ligand)' section.")
    return lines[start_idx : min(start_idx + 300, len(lines))]

def parse_term_from_section(section_lines, term):
    # Match lines like: ∆TOTAL   -7.20   1.87  1.70  0.08  0.07
    pat = re.compile(
        rf"^\s*{DELTA}{re.escape(term)}\s+"
        rf"([-+]?\d+(?:\.\d+)?)\s+"
        rf"([-+]?\d+(?:\.\d+)?)\s+"
        rf"([-+]?\d+(?:\.\d+)?)\s+"
        rf"([-+]?\d+(?:\.\d+)?)\s+"
        rf"([-+]?\d+(?:\.\d+)?)\s*$"
    )
    for ln in section_lines:
        m = pat.match(ln)
        if m:
            avg, sd_prop, sd, sem_prop, sem = map(float, m.groups())
            return {"avg": avg, "sd": sd, "sem": sem, "line": ln}
    return None

# Run
rep_rows = []
rep_vals = {t: [] for t in TERMS}

for rep, fn in rep_files.items():
    p = Path(fn)
    if not p.exists():
        raise FileNotFoundError(f"Missing file: {fn}")

    lines = p.read_text(encoding="utf-8", errors="ignore").splitlines()
    section = extract_delta_section(lines)

    row = {"Replica": rep, "file": fn}
    for term in TERMS:
        got = parse_term_from_section(section, term)
        if got is None:
            row[f"{term} (avg)"] = np.nan
            row[f"{term} (SD within)"] = np.nan
        else:
            row[f"{term} (avg)"] = got["avg"]
            row[f"{term} (SD within)"] = got["sd"]
            rep_vals[term].append(got["avg"])
            if term == "TOTAL":
                row["Matched TOTAL line"] = got["line"]
    rep_rows.append(row)

df_rep = pd.DataFrame(rep_rows)
display(df_rep)

# Save per-replica table
df_rep.to_csv("MMGBSA_per_replica_PAF_summary.csv", index=False, encoding="utf-8-sig")

# Summary mean ± SD across replicas (kcal/mol)
sum_rows = []
for term in TERMS:
    vals = np.array(rep_vals[term], dtype=float)
    if len(vals) != 3:
        sum_rows.append({"Term": term, "Mean ± SD (kcal/mol)": "NA (missing)"})
    else:
        sum_rows.append({"Term": term, "Mean ± SD (kcal/mol)": f"{vals.mean():.2f} ± {vals.std(ddof=1):.2f}"})

df_summary = pd.DataFrame(sum_rows)
df_summary.loc[df_summary["Term"] == "TOTAL", "Term"] = "ΔGbind (ΔTOTAL)"
display(df_summary)

# Save across-replica summary table
df_summary.to_csv("MMGBSA_across_replicas_PAF_summary.csv", index=False, encoding="utf-8-sig")

print("Saved:")
print("- MMGBSA_per_replica_PAF_summary.csv")
print("- MMGBSA_across_replicas_PAF_summary.csv")

,Replica,file,VDWAALS (avg),VDWAALS (SD within),EEL (avg),EEL (SD within),EGB (avg),EGB (SD within),ESURF (avg),ESURF (SD within),GGAS (avg),GGAS (SD within),GSOLV (avg),GSOLV (SD within),TOTAL (avg),TOTAL (SD within),Matched TOTAL line
0,Rep 1,FINAL_RESULTS_MMGBSA_PAF_rep1.dat,-20.74,2.00,-17.93,3.11,32.14,3.70,-2.60,0.26,-38.66,3.54,29.54,3.54,-9.12,1.70,ΔTOTAL -9.12 1.42 ...
1,Rep 2,FINAL_RESULTS_MMGBSA_PAF_rep2.dat,-8.88,2.32,-5.81,3.64,13.68,4.21,-1.12,0.27,-14.69,4.59,12.56,4.10,-2.14,1.34,ΔTOTAL -2.14 1.70 ...
2,Rep 3,FINAL_RESULTS_MMGBSA_PAF_rep3.dat,-15.75,5.28,-4.06,4.05,20.02,7.47,-2.22,0.86,-19.81,7.91,17.80,6.71,-2.01,2.79,ΔTOTAL -2.01 1.60 ...

              Term Mean ± SD (kcal/mol)
0          VDWAALS        -15.12 ± 5.95
1              EEL         -9.27 ± 7.55
2              EGB         21.95 ± 9.38
3            ESURF         -1.98 ± 0.77
4             GGAS       -24.39 ± 12.62
5            GSOLV         19.97 ± 8.69
6  ΔGbind (ΔTOTAL)         -4.42 ± 4.07

Saved:
- MMGBSA_per_replica_PAF_summary.csv
- MMGBSA_across_replicas_PAF_summary.csv

#**MM/GBSA Energy Components - AlphaFold_CAF**

In [6]:
import re
import numpy as np
import pandas as pd
from pathlib import Path

rep_files = {
    "Rep 1": "FINAL_RESULTS_MMGBSA_CAF_rep1.dat",
    "Rep 2": "FINAL_RESULTS_MMGBSA_CAF_rep2.dat",
    "Rep 3": "FINAL_RESULTS_MMGBSA_CAF_rep3.dat",
}

# delta variants: Greek Δ (U+0394) and increment ∆ (U+2206)
DELTA = r"[Δ∆]?"

TERMS = ["VDWAALS", "EEL", "EGB", "ESURF", "GGAS", "GSOLV", "TOTAL"]

def extract_delta_section(lines):
    # Find the header line, then take a window after it
    start_idx = None
    for i, ln in enumerate(lines):
        if "Delta (Complex - Receptor - Ligand)" in ln:
            start_idx = i
            break
    if start_idx is None:
        raise ValueError("Cannot find 'Delta (Complex - Receptor - Ligand)' section.")
    return lines[start_idx : min(start_idx + 300, len(lines))]

def parse_term_from_section(section_lines, term):
    # Match lines like: ∆TOTAL   -7.20   1.87  1.70  0.08  0.07
    pat = re.compile(
        rf"^\s*{DELTA}{re.escape(term)}\s+"
        rf"([-+]?\d+(?:\.\d+)?)\s+"
        rf"([-+]?\d+(?:\.\d+)?)\s+"
        rf"([-+]?\d+(?:\.\d+)?)\s+"
        rf"([-+]?\d+(?:\.\d+)?)\s+"
        rf"([-+]?\d+(?:\.\d+)?)\s*$"
    )
    for ln in section_lines:
        m = pat.match(ln)
        if m:
            avg, sd_prop, sd, sem_prop, sem = map(float, m.groups())
            return {"avg": avg, "sd": sd, "sem": sem, "line": ln}
    return None

# Run
rep_rows = []
rep_vals = {t: [] for t in TERMS}

for rep, fn in rep_files.items():
    p = Path(fn)
    if not p.exists():
        raise FileNotFoundError(f"Missing file: {fn}")

    lines = p.read_text(encoding="utf-8", errors="ignore").splitlines()
    section = extract_delta_section(lines)

    row = {"Replica": rep, "file": fn}
    for term in TERMS:
        got = parse_term_from_section(section, term)
        if got is None:
            row[f"{term} (avg)"] = np.nan
            row[f"{term} (SD within)"] = np.nan
        else:
            row[f"{term} (avg)"] = got["avg"]
            row[f"{term} (SD within)"] = got["sd"]
            rep_vals[term].append(got["avg"])
            if term == "TOTAL":
                row["Matched TOTAL line"] = got["line"]
    rep_rows.append(row)

df_rep = pd.DataFrame(rep_rows)
display(df_rep)

# Save per-replica table
df_rep.to_csv("MMGBSA_per_replica_CAF_summary.csv", index=False, encoding="utf-8-sig")

# Summary mean ± SD across replicas (kcal/mol)
sum_rows = []
for term in TERMS:
    vals = np.array(rep_vals[term], dtype=float)
    if len(vals) != 3:
        sum_rows.append({"Term": term, "Mean ± SD (kcal/mol)": "NA (missing)"})
    else:
        sum_rows.append({"Term": term, "Mean ± SD (kcal/mol)": f"{vals.mean():.2f} ± {vals.std(ddof=1):.2f}"})

df_summary = pd.DataFrame(sum_rows)
df_summary.loc[df_summary["Term"] == "TOTAL", "Term"] = "ΔGbind (ΔTOTAL)"
display(df_summary)

# Save across-replica summary table
df_summary.to_csv("MMGBSA_across_replicas_CAF_summary.csv", index=False, encoding="utf-8-sig")

print("Saved:")
print("- MMGBSA_per_replica_CAF_summary.csv")
print("- MMGBSA_across_replicas_CAF_summary.csv")

,Replica,file,VDWAALS (avg),VDWAALS (SD within),EEL (avg),EEL (SD within),EGB (avg),EGB (SD within),ESURF (avg),ESURF (SD within),GGAS (avg),GGAS (SD within),GSOLV (avg),GSOLV (SD within),TOTAL (avg),TOTAL (SD within),Matched TOTAL line
0,Rep 1,FINAL_RESULTS_MMGBSA_CAF_rep1.dat,-17.61,1.69,-8.70,2.08,21.85,1.91,-2.62,0.18,-26.31,2.32,19.23,1.84,-7.08,1.44,ΔTOTAL -7.08 1.95 ...
1,Rep 2,FINAL_RESULTS_MMGBSA_CAF_rep2.dat,-9.92,2.79,-4.25,3.35,13.13,3.84,-1.45,0.47,-14.16,4.89,11.69,3.45,-2.48,1.85,ΔTOTAL -2.48 1.78 ...
2,Rep 3,FINAL_RESULTS_MMGBSA_CAF_rep3.dat,-8.37,3.56,2.00,2.38,4.75,3.18,-1.07,0.52,-6.37,4.74,3.68,2.84,-2.70,2.44,ΔTOTAL -2.70 1.55 ...

              Term Mean ± SD (kcal/mol)
0          VDWAALS        -11.97 ± 4.95
1              EEL         -3.65 ± 5.38
2              EGB         13.24 ± 8.55
3            ESURF         -1.71 ± 0.81
4             GGAS       -15.61 ± 10.05
5            GSOLV         11.53 ± 7.78
6  ΔGbind (ΔTOTAL)         -4.09 ± 2.59

Saved:
- MMGBSA_per_replica_CAF_summary.csv
- MMGBSA_across_replicas_CAF_summary.csv

#**MM/GBSA Summary Across All Systems**

In [7]:
import pandas as pd
from pathlib import Path

# ---------------------------
# Input files
# ---------------------------
per_replica_files = {
    "holo": "MMGBSA_per_replica_5FWJ metal-retained_summary.csv",
    "apo": "MMGBSA_per_replica_5FWJ metal-depleted_summary.csv",
    "PAF": "MMGBSA_per_replica_PAF_summary.csv",
    "CAF": "MMGBSA_per_replica_CAF_summary.csv",
}

across_replica_files = {
    "holo": "MMGBSA_across_replicas_5FWJ metal-retained_summary.csv",
    "apo": "MMGBSA_across_replicas_5FWJ metal-depleted_summary.csv",
    "PAF": "MMGBSA_across_replicas_PAF_summary.csv",
    "CAF": "MMGBSA_across_replicas_CAF_summary.csv",
}

# ---------------------------
# Combine per-replica tables
# ---------------------------
per_replica_dfs = []

for system, fn in per_replica_files.items():
    p = Path(fn)
    if not p.exists():
        raise FileNotFoundError(f"Missing file: {fn}")

    df = pd.read_csv(p)
    df.insert(0, "System", system)   # add System as first column
    per_replica_dfs.append(df)

df_per_replica_all = pd.concat(per_replica_dfs, ignore_index=True)
display(df_per_replica_all)

df_per_replica_all.to_csv(
    "MMGBSA_per_replica_all_systems.csv",
    index=False,
    encoding="utf-8-sig"
)

# ---------------------------
# Combine across-replica tables
# ---------------------------
across_replica_dfs = []

for system, fn in across_replica_files.items():
    p = Path(fn)
    if not p.exists():
        raise FileNotFoundError(f"Missing file: {fn}")

    df = pd.read_csv(p)
    df.insert(0, "System", system)   # add System as first column
    across_replica_dfs.append(df)

df_across_replica_all = pd.concat(across_replica_dfs, ignore_index=True)
display(df_across_replica_all)

df_across_replica_all.to_csv(
    "MMGBSA_across_replicas_all_systems.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Saved:")
print("- MMGBSA_per_replica_all_systems.csv")
print("- MMGBSA_across_replicas_all_systems.csv")

,System,Replica,file,VDWAALS (avg),VDWAALS (SD within),EEL (avg),EEL (SD within),EGB (avg),EGB (SD within),ESURF (avg),ESURF (SD within),GGAS (avg),GGAS (SD within),GSOLV (avg),GSOLV (SD within),TOTAL (avg),TOTAL (SD within),Matched TOTAL line
0,holo,Rep 1,FINAL_RESULTS_MMGBSA_holo_rep1.dat,-5.01,7.38,-1.64,3.82,5.21,7.53,-0.67,1.01,-6.66,10.23,4.54,6.64,-2.12,4.21,ΔTOTAL -2.12 1.70 ...
1,holo,Rep 2,FINAL_RESULTS_MMGBSA_holo_rep2.dat,-21.93,2.39,-7.83,3.32,30.08,3.58,-2.85,0.32,-29.76,4.57,27.24,3.47,-2.53,3.74,ΔTOTAL -2.53 1.57 ...
2,holo,Rep 3,FINAL_RESULTS_MMGBSA_holo_rep3.dat,-0.00,0.01,-0.14,1.40,0.31,1.60,-0.00,0.00,-0.14,1.41,0.31,1.60,0.16,0.50,ΔTOTAL 0.16 1.87 ...
3,apo,Rep 1,FINAL_RESULTS_MMGBSA_apo_rep1.dat,-0.00,0.00,0.00,0.11,-0.00,0.11,0.00,0.00,0.00,0.11,-0.00,0.11,-0.00,0.00,ΔTOTAL -0.00 2.00 ...
4,apo,Rep 2,FINAL_RESULTS_MMGBSA_apo_rep2.dat,-9.55,8.16,-1.26,2.01,5.39,4.48,-1.17,0.97,-10.82,9.29,4.22,3.58,-6.60,6.00,ΔTOTAL -6.60 1.42 ...
5,apo,Rep 3,FINAL_RESULTS_MMGBSA_apo_rep3.dat,-6.65,5.70,-0.70,1.60,4.42,3.55,-0.93,0.83,-7.36,6.54,3.49,2.83,-3.87,4.03,ΔTOTAL -3.87 1.51 ...
6,PAF,Rep 1,FINAL_RESULTS_MMGBSA_PAF_rep1.dat,-20.74,2.00,-17.93,3.11,32.14,3.70,-2.60,0.26,-38.66,3.54,29.54,3.54,-9.12,1.70,ΔTOTAL -9.12 1.42 ...
7,PAF,Rep 2,FINAL_RESULTS_MMGBSA_PAF_rep2.dat,-8.88,2.32,-5.81,3.64,13.68,4.21,-1.12,0.27,-14.69,4.59,12.56,4.10,-2.14,1.34,ΔTOTAL -2.14 1.70 ...
8,PAF,Rep 3,FINAL_RESULTS_MMGBSA_PAF_rep3.dat,-15.75,5.28,-4.06,4.05,20.02,7.47,-2.22,0.86,-19.81,7.91,17.80,6.71,-2.01,2.79,ΔTOTAL -2.01 1.60 ...
9,CAF,Rep 1,FINAL_RESULTS_MMGBSA_CAF_rep1.dat,-17.61,1.69,-8.70,2.08,21.85,1.91,-2.62,0.18,-26.31,2.32,19.23,1.84,-7.08,1.44,ΔTOTAL -7.08 1.95 ...
10,CAF,Rep 2,FINAL_RESULTS_MMGBSA_CAF_rep2.dat,-9.92,2.79,-4.25,3.35,13.13,3.84,-1.45,0.47,-14.16,4.89,11.69,3.45,-2.48,1.85,ΔTOTAL -2.48 1.78 ...
11,CAF,Rep 3,FINAL_RESULTS_MMGBSA_CAF_rep3.dat,-8.37,3.56,2.00,2.38,4.75,3.18,-1.07,0.52,-6.37,4.74,3.68,2.84,-2.70,2.44,ΔTOTAL -2.70 1.55 ...

   System             Term Mean ± SD (kcal/mol)
0    holo          VDWAALS        -8.98 ± 11.49
1    holo              EEL         -3.20 ± 4.08
2    holo              EGB        11.87 ± 15.96
3    holo            ESURF         -1.17 ± 1.49
4    holo             GGAS       -12.19 ± 15.56
5    holo            GSOLV        10.70 ± 14.48
6    holo  ΔGbind (ΔTOTAL)         -1.50 ± 1.45
7     apo          VDWAALS         -5.40 ± 4.90
8     apo              EEL         -0.65 ± 0.63
9     apo              EGB          3.27 ± 2.87
10    apo            ESURF         -0.70 ± 0.62
11    apo             GGAS         -6.06 ± 5.53
12    apo            GSOLV          2.57 ± 2.26
13    apo  ΔGbind (ΔTOTAL)         -3.49 ± 3.32
14    PAF          VDWAALS        -15.12 ± 5.95
15    PAF              EEL         -9.27 ± 7.55
16    PAF              EGB         21.95 ± 9.38
17    PAF            ESURF         -1.98 ± 0.77
18    PAF             GGAS       -24.39 ± 12.62
19    PAF            GSOLV         19.97 ± 8.69
20    PAF  ΔGbind (ΔTOTAL)         -4.42 ± 4.07
21    CAF          VDWAALS        -11.97 ± 4.95
22    CAF              EEL         -3.65 ± 5.38
23    CAF              EGB         13.24 ± 8.55
24    CAF            ESURF         -1.71 ± 0.81
25    CAF             GGAS       -15.61 ± 10.05
26    CAF            GSOLV         11.53 ± 7.78
27    CAF  ΔGbind (ΔTOTAL)         -4.09 ± 2.59

Saved:
- MMGBSA_per_replica_all_systems.csv
- MMGBSA_across_replicas_all_systems.csv